"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Sparkles, TrendingUp, TrendingDown, Loader2 } from "lucide-react";
import { useCura } from "@/lib/store/useCura";
import type { Insights } from "@/lib/ai/recommendations";

export default function Page() {
  const twin = useCura((s) => s.twin);
  const [data, setData] = useState<Insights | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      setLoading(true);
      try {
        const res = await fetch("/api/insights", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ twin: twin ?? {}, activity: { completed_tasks: 12, streak_days: 9, last_session: "Hydra-facial" } }),
        });
        setData(await res.json());
      } finally { setLoading(false); }
    })();
  }, [twin]);

  return (
    <div className="max-w-6xl mx-auto px-4 pt-12 pb-24">
      <div className="mb-8">
        <div className="chip mb-3"><Sparkles className="w-3 h-3" /> Beauty Insights</div>
        <h1 className="font-display text-4xl md:text-5xl tracking-tight">
          Your beauty, <span className="text-grad">measured.</span>
        </h1>
        <p className="text-muted mt-3 max-w-xl">A weekly synthesis generated by CURA from your profile, sessions, and routine.</p>
      </div>

      {loading || !data ? (
        <div className="grid md:grid-cols-3 gap-5">
          {Array.from({ length: 6 }).map((_, i) => (
            <div key={i} className="glass rounded-2xl p-5 h-44 relative overflow-hidden">
              <div className="shimmer absolute inset-0" />
            </div>
          ))}
        </div>
      ) : (
        <>
          {/* Top: score */}
          <div className="grid md:grid-cols-[1.2fr_1fr_1fr] gap-5">
            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass-strong rounded-2xl p-6 relative overflow-hidden">
              <div className="absolute -top-20 right-0 w-72 h-72 rounded-full bg-violet/30 blur-3xl" />
              <div className="relative">
                <div className="text-xs text-muted">Beauty Score</div>
                <div className="flex items-end gap-3 mt-1">
                  <div className="font-display text-7xl text-grad leading-none">{data.beauty_score}</div>
                  <div className="text-xs text-cyan flex items-center gap-1 mb-2">
                    <TrendingUp className="w-3 h-3" /> +{data.score_delta} this week
                  </div>
                </div>
                <div className="mt-3 text-xs text-muted">Next milestone</div>
                <div className="text-sm text-ink mt-0.5">{data.next_milestone}</div>
              </div>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }} className="glass rounded-2xl p-6">
              <div className="chip mb-3 inline-flex"><TrendingUp className="w-3 h-3" /> Strengths</div>
              <div className="space-y-3">
                {data.strengths.map((s) => (
                  <div key={s.label}>
                    <div className="flex justify-between text-xs"><span className="text-ink">{s.label}</span><span className="text-cyan">{s.score}</span></div>
                    <div className="h-1.5 rounded-full bg-white/5 overflow-hidden mt-1">
                      <motion.div initial={{ width: 0 }} animate={{ width: `${s.score}%` }} transition={{ duration: 0.8 }} className="h-full bg-gradient-to-r from-cyan to-aurora" />
                    </div>
                    <div className="text-[11px] text-muted mt-1">{s.note}</div>
                  </div>
                ))}
              </div>
            </motion.div>

            <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="glass rounded-2xl p-6">
              <div className="chip mb-3 inline-flex"><TrendingDown className="w-3 h-3" /> Areas to improve</div>
              <div className="space-y-3">
                {data.improvements.map((s) => (
                  <div key={s.label}>
                    <div className="flex justify-between text-xs"><span className="text-ink">{s.label}</span><span className="text-plasma">{s.score}</span></div>
                    <div className="h-1.5 rounded-full bg-white/5 overflow-hidden mt-1">
                      <motion.div initial={{ width: 0 }} animate={{ width: `${s.score}%` }} transition={{ duration: 0.8 }} className="h-full bg-gradient-to-r from-plasma to-violet" />
                    </div>
                    <div className="text-[11px] text-muted mt-1">{s.note}</div>
                  </div>
                ))}
              </div>
            </motion.div>
          </div>

          {/* Bottom */}
          <div className="grid md:grid-cols-[2fr_1fr] gap-5 mt-5">
            <div className="glass rounded-2xl p-6">
              <div className="chip mb-3">Weekly recommendations</div>
              <div className="grid sm:grid-cols-2 gap-3">
                {data.weekly_recommendations.map((r) => (
                  <div key={r.title} className="p-4 rounded-xl bg-white/[0.03] border border-white/5">
                    <div className="text-xs text-muted uppercase tracking-wider">{r.category}</div>
                    <div className="text-sm text-ink font-medium mt-1">{r.title}</div>
                    <div className="text-xs text-muted mt-1">{r.why}</div>
                  </div>
                ))}
              </div>
            </div>
            <div className="glass rounded-2xl p-6">
              <div className="chip mb-3">Trending for you</div>
              <div className="space-y-2">
                {data.trending_for_you.map((t, i) => (
                  <div key={t} className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.03] border border-white/5">
                    <div className="w-6 h-6 rounded-full bg-gradient-to-br from-violet to-cyan flex items-center justify-center text-[10px] font-display">{i + 1}</div>
                    <div className="text-sm text-ink">{t}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}
